{
 "title": "Vault Ingress",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[1m]))",
     "legendFormat": "Globlal RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_health_check_attempt[1m]))",
     "legendFormat": "Global HC RPS"
    },
    {
     "expr": "sum(rate(envoy_http_rq_total[1m]))",
     "legendFormat": "Global Routed RPS"
    }
   ]
  },
  {
   "title": "Global CPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[1m]))",
     "legendFormat": "Global CPS"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[1m])) / sum(rate(envoy_http_downstream_rq_xx[1m]))))",
     "legendFormat": "SR"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active)",
     "legendFormat": "Downstream Connections"
    },
    {
     "expr": "sum(envoy_server_parent_connections)",
     "legendFormat": "Downstream Parent Connections"
    },
    {
     "expr": "sum(envoy_cluster_upstream_cx_http1_total)",
     "legendFormat": "Upstream HTTP/1.1 Connections"
    },
    {
     "expr": "sum(envoy_cluster_upstream_cx_http2_total)",
     "legendFormat": "Upstream HTTP/2 Connections"
    }
   ]
  },
  {
   "title": "Upstream failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject[1m]))",
     "legendFormat": "Pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow[1m]))",
     "legendFormat": "Pending Overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout[1m]))",
     "legendFormat": "Connect Timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout[1m]))",
     "legendFormat": "Request Timeout"
    }
   ]
  },
  {
   "title": "Upstream Retries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry[1m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success[1m]))",
     "legendFormat": "Retry Success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow[1m]))",
     "legendFormat": "Retry Overflow"
    }
   ]
  },
  {
   "title": "Outlier Detection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_enforced_total[1m]))",
     "legendFormat": "Total Ejections"
    },
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_overflow[1m]))",
     "legendFormat": "Total Ejection Overflows"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((sum(rate(envoy_cluster_health_check_success[1m])) / sum(rate(envoy_cluster_health_check_attempt[1m]))))",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_difference(max(\"bytes_recv\")) + non_negative_difference(max(\"bytes_sent\")) AS \"bytes\" FROM \"telegraf\".\"autogen\".\"net\" WHERE (\"role\" = 'envoy-server') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "consul-server" }
     ]
    }
   ]
  },
  {
   "title": "Runtime Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.runtime.alloc_bytes",
     "query": "SELECT max(\"value\") AS \"alloc_bytes\" FROM \"telegraf\".\"autogen\".\"vault.runtime.alloc_bytes\" WHERE (\"role\" = 'envoy-server') AND $timeFilter GROUP BY time($__interval), \"host\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"sys_bytes\" FROM \"telegraf\".\"autogen\".\"vault.runtime.sys_bytes\" WHERE (\"role\" = 'envoy-server' ) AND $timeFilter GROUP BY time($__interval), \"host\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"total\") AS \"total_bytes\" FROM \"telegraf\".\"autogen\".\"mem\" WHERE (\"role\" = 'envoy-server') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datacenter", "operator": "=~", "value": "/^$dc$/" },
      { "condition": "AND", "key": "role", "operator": "=", "value": "vault-server" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"usage_user\") AS \"user_cpu\", max(\"usage_iowait\") AS \"iowait_cpu\" FROM \"telegraf\".\"autogen\".\"cpu\" WHERE (\"role\" = 'envoy-server') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"usage_user\") AS \"user_cpu\", max(\"usage_iowait\") AS \"iowait_cpu\" FROM \"telegraf\".\"autogen\".\"cpu\" WHERE (\"role\" = 'envoy-server') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    }
   ]
  },
  {
   "title": "Min Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "min(envoy_server_version)" }
   ]
  },
  {
   "title": "Max Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(envoy_server_version)" }
   ]
  }
 ]
}