name 'hashicorp_vault_examples'
maintainer 'The Authors'
maintainer_email ''
license ''
description 'Installs/Configures hashicorp_vault_examples'
long_description 'Installs/Configures hashicorp_vault_examples'
version '0.1.0'
