$base = <<BASE
sudo yum install -q -y wget unzip
sudo curl -s -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 > /usr/bin/jq
sudo chmod +x /usr/bin/jq
BASE

$postgres = <<POSTGRES
sleep 10
sudo yum install -q -y postgresql
psql -h localhost -U postgres -d postgres -a -f /vagrant/scripts/postgres.sql
POSTGRES

$vault = <<VAULT
#Get Vault
VAULT=0.10.0
VAULT_ZIP=/vagrant/bin/vault_${VAULT}_linux_amd64.zip
if [ ! -f $VAULT_ZIP ]; then
  mkdir -p /vagrant/bin
  wget https://releases.hashicorp.com/vault/${VAULT}/vault_${VAULT}_linux_amd64.zip --quiet -O $VAULT_ZIP
fi
cd /tmp
unzip -q $VAULT_ZIP >/dev/null
sudo chmod +x vault
sudo mv vault /usr/bin
sudo chmod 0755 /usr/bin/vault
sudo chown root:root /usr/bin/vault

#Create Policy
export VAULT_ADDR=http://127.0.0.1:8200
vault login root
chmod +x /vagrant/scripts/vault.sh
/vagrant/scripts/vault.sh
VAULT

$spring = <<SPRING
sudo wget -q http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
sudo yum install -q -y apache-maven
cd /vagrant
mvn package
docker build --build-arg JAR_FILE=target/spring-vault-demo-1.0.jar -t spring .
SPRING

Vagrant.configure("2") do |config|
  config.vm.synced_folder "../", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end
  config.vm.define "demo" do |demo|
    demo.vm.box = "bento/centos-7.4"
    demo.vm.hostname = "demo.example.com"
    demo.vm.network "private_network", type: "dhcp"
    demo.vm.network :private_network, ip: "192.168.50.151"
    demo.vm.network :forwarded_port, guest: 8200, host: 8200
    demo.vm.network :forwarded_port, guest: 8080, host: 8080
    demo.vm.network :forwarded_port, guest: 5432, host: 5432
    demo.vm.provision "shell", inline: $base
    demo.vm.provision "docker" do |d|
      d.run "postgres",
        args: "--net=host -d"
      d.run "vault",
        args: "--net=host --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=root' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' -d"
    end
    demo.vm.provision "shell", inline: $postgres
    demo.vm.provision "shell", inline: $vault, run: "always"
    demo.vm.provision "shell", inline: $spring
    demo.vm.provision "docker" do |d|
    d.run "spring",
      args: "--net=host -p 8080:8080 -v /vagrant/bootstrap.yaml:/bootstrap.yaml -e 'VAULT_TOKEN=root' -d"
    end
  end
end
