
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vault variable defaults
vault_version = ENV['VAULT_VERSION'] || "1.2.1"
vault_ent_url = ENV['VAULT_ENT_URL']
vault_group = "vault"
vault_user = "vault"
vault_comment = "Vault"
vault_home = "/srv/vault"

$vault_env = <<VAULT_ENV
sudo cat << EOF > /etc/profile.d/vault.sh
export VAULT_ADDR="http://192.168.50.100:8200"
export VAULT_SKIP_VERIFY=true
EOF
VAULT_ENV

$vault_run = <<VAULT_RUN
nohup /usr/local/bin/vault server -dev \
  -dev-root-token-id="password" \
  -dev-listen-address="0.0.0.0:8200" 0<&- &>/dev/null &
VAULT_RUN

# vagrant-hosts plugin is required
required_plugins = %w(vagrant-hosts)
return if !Vagrant.plugins_enabled?
plugins_to_install = required_plugins.select { |plugin| !Vagrant.has_plugin? plugin }
if plugins_to_install.any?
  system "vagrant plugin install #{plugins_to_install.join(' ')}"
  exit system 'vagrant up'
end

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.customize ["modifyvm", :id, "--chipset", "ich9"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  config.vm.define "vault" do |vault|
    vault.vm.network :private_network, ip: "192.168.50.100"
    vault.vm.provision :hosts, sync_hosts: true
    vault.vm.box = "bento/centos-7.6"
    vault.vm.box_version = "201812.27.0"
    vault.vm.hostname = "vault"
    vault.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/shared/scripts/base.sh | bash"
    vault.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/shared/scripts/setup-user.sh | bash",
      env: {
        "GROUP" => vault_group,
        "USER" => vault_user,
        "COMMENT" => vault_comment,
        "HOME" => vault_home,
      }
    vault.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/vault/scripts/install-vault.sh | bash",
      env: {
        "VERSION" => vault_version,
        "URL" => vault_ent_url,
        "USER" => vault_user,
        "GROUP" => vault_group,
      }
    vault.vm.provision "shell", inline: $vault_env
    vault.vm.provision "shell", inline: $vault_run
  end

  config.vm.define "client" do |client|
    client.vm.network :private_network, ip: "192.168.50.101"
    client.vm.provision :hosts, sync_hosts: true
    client.vm.box = "bento/centos-7.6"
    client.vm.box_version = "201812.27.0"
    client.vm.hostname = "client"
    client.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/shared/scripts/base.sh | bash"
    client.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/shared/scripts/setup-user.sh | bash",
      env: {
        "GROUP" => vault_group,
        "USER" => vault_user,
        "COMMENT" => vault_comment,
        "HOME" => vault_home,
      }
    client.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/vault/scripts/install-vault.sh | bash",
      env: {
        "VERSION" => vault_version,
        "URL" => vault_ent_url,
        "USER" => vault_user,
        "GROUP" => vault_group,
      }
    client.vm.provision "shell", inline: $vault_env
  end
end
