spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "exampleapp"
        vault.hashicorp.com/agent-inject-secret-exampleapp-config: "secret/exampleapp/config"
