apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleapp
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: exampleapp
      containers:
        - name: exampleapp
          image: jweissig/app:0.0.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exampleapp
  labels:
    app: vault-agent-demo
