
# -*- mode: ruby -*-
# vi: set ft=ruby :

# vault variable defaults
vault_version = ENV['VAULT_VERSION'] || "0.8.3"
vault_download_url = ENV['VAULT_ENT_URL'] || "https://releases.hashicorp.com/vault/#{vault_version}/vault_#{vault_version}_linux_amd64.zip"

$vault_env = <<VAULT_ENV
sudo cat << EOF > /etc/profile.d/vault.sh
export VAULT_ADDR="http://192.168.50.100:8200"
export VAULT_SKIP_VERIFY=true
EOF
VAULT_ENV

$vault_run = <<VAULT_RUN
nohup /usr/local/bin/vault server -dev \
  -dev-root-token-id="password" \
  -dev-listen-address="0.0.0.0:8200" 0<&- &>/dev/null &
VAULT_RUN

$hosts_file = <<HOSTS_FILE
sudo cat << EOF >> /etc/hosts
192.168.50.100  vault vault.example.com
192.168.50.101  client client.example.com
EOF
HOSTS_FILE

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.customize ["modifyvm", :id, "--chipset", "ich9"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  config.vm.define "vault" do |vault|
    vault.vm.network :private_network, ip: "192.168.50.100"
    vault.vm.box = "bento/centos-7.3"
    vault.vm.box_version = "2.3.8"
    vault.vm.hostname = "vault"
    vault.vm.provision "shell", path: "../../../shared/scripts/base.sh"
    vault.vm.provision "shell", path: "../../../shared/scripts/setup-user.sh", args: "vault"
    vault.vm.provision "shell", path: "../../../shared/vault/scripts/install-vault.sh",
    env: { "VERSION" => vault_version,"URL" => vault_download_url }
    vault.vm.provision "shell", inline: $vault_env
    vault.vm.provision "shell", inline: $vault_run
    vault.vm.provision "shell", inline: $hosts_file
  end

  config.vm.define "client" do |client|
    client.vm.network :private_network, ip: "192.168.50.101"
    client.vm.box = "bento/centos-7.3"
    client.vm.box_version = "2.3.8"
    client.vm.hostname = "client"
    client.vm.provision "shell", path: "../../../shared/scripts/base.sh"
    client.vm.provision "shell", path: "../../../shared/scripts/setup-user.sh", args: "vault"
    client.vm.provision "shell", path: "../../../shared/vault/scripts/install-vault.sh",
    env: { "VERSION" => vault_version,"URL" => vault_download_url }
    client.vm.provision "shell", inline: $vault_env
    client.vm.provision "shell", inline: $hosts_file
  end
end

