$base = <<BASE
sudo yum install -q -y wget vim-enhanced unzip ca-certificates
sudo curl -s -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 > /usr/local/bin/jq
sudo chmod +x /usr/local/bin/jq
BASE

$vault_install = <<VAULT_INST
VAULT=0.8.3
VAULT_ZIP=/vagrant/bin/vault_${VAULT}_linux_amd64.zip
if [ ! -f $VAULT_ZIP ]; then
  mkdir -p /vagrant/bin
  wget https://releases.hashicorp.com/vault/${VAULT}/vault_${VAULT}_linux_amd64.zip --quiet -O $VAULT_ZIP
fi
cd /tmp
unzip -q $VAULT_ZIP >/dev/null
sudo chmod +x vault
sudo mv vault /usr/local/bin
sudo chmod 0755 /usr/local/bin/vault
sudo chown root:root /usr/local/bin/vault
VAULT_INST

$vault_env = <<VAULT_ENV
sudo cat << EOF > /etc/profile.d/vault.sh
export VAULT_ADDR="http://192.168.50.100:8200"
export VAULT_SKIP_VERIFY=true
EOF
VAULT_ENV

$vault_run = <<VAULT_RUN
nohup /usr/local/bin/vault server -dev \
  -dev-root-token-id="password" \
  -dev-listen-address="0.0.0.0:8200" 0<&- &>/dev/null &
VAULT_RUN

$hosts_file = <<HOSTS_FILE
sudo cat << EOF >> /etc/hosts
192.168.50.100  vault vault.example.com
192.168.50.101  client client.example.com
EOF
HOSTS_FILE

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.customize ["modifyvm", :id, "--chipset", "ich9"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  config.vm.define "vault" do |vault|
    vault.vm.network :private_network, ip: "192.168.50.100"
    vault.vm.box = "bento/centos-7.3"
    vault.vm.hostname = "vault"
    vault.vm.provision "shell", inline: $base
    vault.vm.provision "shell", inline: $vault_install
    vault.vm.provision "shell", inline: $vault_env
    vault.vm.provision "shell", inline: $vault_run
    vault.vm.provision "shell", inline: $hosts_file
  end

  config.vm.define "client" do |client|
    client.vm.network :private_network, ip: "192.168.50.101"
    client.vm.box = "bento/centos-7.3"
    client.vm.hostname = "client"
    client.vm.provision "shell", inline: $base
    client.vm.provision "shell", inline: $vault_install
    client.vm.provision "shell", inline: $vault_env
    client.vm.provision "shell", inline: $hosts_file
  end
end
