global:
  datacenter: hashidc1

ui:
  service:
    type: "LoadBalancer"

connectInject:
  enabled: true

client:
  enabled: true
  grpc: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
