---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleapp-simple
  labels:
    app: exampleapp-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp-simple
  template:
    metadata:
      labels:
        app: exampleapp-simple
    spec:
      serviceAccountName: vault
      containers:
      - name: app
        image: malnick/exampleapp:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: CONFIG_FILE
          value: "/etc/secrets/exampleapp"
