# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

global:
  datacenter: vault-kubernetes-guide

client:
  enabled: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    maxUnavailable: 0