version: "3.3"
services:

  vault-agent:
    image: vault:1.11.0
    restart: always
    command: [ 'vault', 'agent', '-config=/vault/ProjectApi/vault-agent/config-vault-agent-template.hcl']
    volumes:
      - ./ProjectApi:/vault/ProjectApi:rw
    cap_add:
      - IPC_LOCK
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

networks:
  vpcbr:
    external:
      name: dotnet-vault_vpcbr