---

apiVersion: v1
kind: Service
metadata:
  name: "consul-ui"
spec:
  type: NodePort
  ports:
    - name: "ui"
      port: 8500
      protocol: TCP
  selector:
    app: consul
    role: server
    quorum: voting

---

apiVersion: v1
kind: Service
metadata:
  name: "consul"
spec:
  ports:
    - name: "rpc"
      port: 8300
    - name: "lan"
      port: 8301
    - name: "wan"
      port: 8302
    - name: "api"
      port: 8500
      protocol: TCP
    - name: "dns-udp"
      port: 8600
      protocol: UDP
    - name: "dns-tcp"
      port: 8600
      protocol: TCP
  clusterIP: None
  selector:
    app: consul
    role: server
    quorum: voting

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-local-config
data:
  local.config: |
    {
      "server": true,
      "client_addr": "0.0.0.0",
      "ui": true,
      "bind_addr": "0.0.0.0",
      "bootstrap_expect": 3,
      "raft_protocol": 3,
      "retry_join": [
        "consul-0.consul",
        "consul-1.consul",
        "consul-2.consul",
        "consul-3.consul",
        "consul-4.consul"
      ]
    }

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
      role: server
      quorum: voting
  serviceName: "consul"
  replicas: 5
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consul
        role: server
        quorum: voting
    spec:
      containers:
      - name: consul-server
        image: consul-enterprise
        imagePullPolicy: Never
        env:
          - name: CONSUL_LOCAL_CONFIG
            valueFrom:
              configMapKeyRef:
                name: consul-local-config
                key: local.config
        command: [ "docker-entrypoint.sh" ]
        args: [ "agent", "-config-file", "/consul/config/local.json" ]
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep consul
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /v1/status/peers
            port: 8500
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8500
          name: api
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
        - containerPort: 8600
          name: dns-tcp
          protocol: TCP
        volumeMounts:
        - name: consul-config
          mountPath: /consul/config
        - name: consul-data
          mountPath: /consul/data
  volumeClaimTemplates:
  - metadata:
      name: consul-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Mi
  - metadata:
      name: consul-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
