---

apiVersion: v1
kind: Service
metadata:
  name: "vault-ui"
spec:
  type: NodePort
  ports:
    - name: "ui"
      port: 8200
      protocol: TCP
  selector:
    app: vault
    role: server

---

apiVersion: v1
kind: Service
metadata:
  name: "vault"
spec:
  ports:
    - name: "api"
      port: 8200
    - name: "rpc"
      port: 8201
  clusterIP: None
  selector:
    app: vault
    role: server

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-local-config
data:
  local.config: |
    {
      "ui": true,
      "listener": [{
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": true
        }
      }],
      "storage": [{
        "consul": {
          "address": "localhost:8500",
          "schema": "http",
          "path": "vault"
        }
      }]
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-consul-local-config
data:
  local.config: |
    {
      "server": false,
      "client_addr": "127.0.0.1",
      "ui": false,
      "raft_protocol": 3,
      "retry_join": [
        "consul-0.consul",
        "consul-1.consul",
        "consul-2.consul",
        "consul-3.consul",
        "consul-4.consul"
      ]
    }

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
    role: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vault
      role: server
  template:
    metadata:
      labels:
        app: vault
        role: server
    spec:
      containers:
      - name: vault
        image: vault-enterprise
        imagePullPolicy: Never
        securityContext:
          capabilities:
            add: [ "IPC_LOCK" ]
        env:
        - name: VAULT_LOCAL_CONFIG
          valueFrom:
            configMapKeyRef:
              name: vault-local-config
              key: local.config
        args: [ "server" ]
        livenessProbe:
          exec:
            command:
            - pidof
            - vault
          initialDelaySeconds: 5
          timeoutSeconds: 2
        ports:
        - containerPort: 8200
          name: api
      - name: consul-client
        image: consul-enterprise
        imagePullPolicy: Never
        env:
          - name: CONSUL_LOCAL_CONFIG
            valueFrom:
              configMapKeyRef:
                name: vault-consul-local-config
                key: local.config
        command: [ "docker-entrypoint.sh" ]
        args: [ "agent", "-config-file", "/consul/config/local.json"]
        livenessProbe:
          exec:
            command:
            - pidof
            - consul
          initialDelaySeconds: 5
          timeoutSeconds: 2
        ports:
        - containerPort: 8500
          name: api
